version = 0.1

[default.global.parameters]
stack_name = "fraud-detector"
resolve_s3 = true
resolve_image_repos = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false

[default.deploy.parameters]
region = "us-east-1"
